# Generated by Django 4.0.4 on 2022-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='data/pics')),
                ('email', models.EmailField(max_length=120)),
                ('userName', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
